[[override]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/client-go"
  branch = "release-5.0"
